# Example register map toml

# Module definition
module-name = "regmap"
register-width = 32

# Array of tables of bitfields
[[bitfield]]
name = "mask"
width = 2
default-value = 0b01
access = "RW"

[[bitfield]]
name = "flag"
width = 1
default-value = 0b11
access = "RO"

[[bitfield]]
name = "enable"
width = 1
default-value = 0b0
access = "RW"

[[bitfield]]
name = "test1"
default-value = 0b0
access = "RW"

[[bitfield]]
name = "test1"
width = 1
default-value = 0b0
access = "RWI"

[[register]]
name = "reg0"
address = 0x0000_0000
repetition = { times = 0, address-increment = 0x0000_0004 }
bitfield-reference = [
  { reg-offset = 0, slice-start-idx = 0, slice-width = 2, bf-name = "mask" },
  { reg-offset = 0, slice-start-idx = 0, slice-width = 1, bf-name = "enable" },
]

[[register]]
name = "reg1"
address = 0x0000_0000
repetition = { times = 1, address-increment = 0x0000_0004 }
bitfield-reference = [
  { reg-offset = 0, slice-start-idx = 0, slice-width = 1, bf-name = "flag" },
]

